### ISSUE TITLE
Create a project directly from a webhook

### ISSUE THREAD

**Issue by alejandrogr** [BBVA/deeptracy#27]
We want to be able to create projects directly from a webhook (GitHub&Bitbucket).

This feature can be only achieved for PUBLIC projects.
This feature involves making a pull for the repository and determining the default language (by examining the files in the repo) for future scans.

**Comment by alejandrogr** [comment]
We should consider adding a .deeptracy file to the repository root. My proposal is to use a yml file

.deeptracy.yml

```
language: nodejs
plugins:
  - retirejs
notify:
  - hook: slack
    webhook: http://slack.weebhook/test
```

Right now we only need the language, but this give us enough power to add more things in the future. I think we can follow travis.yml file as a guide.

The first iteration of this feature will be only for public projects from GitHub.
